### ISSUE TITLE
target の index について

### ISSUE THREAD

**Issue by kosukemtr** [ken-nakanishi/qupy#1]
q = Qubits(4)
q.gate(qupy.operator.H, target = 1)

みたいに使うと思いますが、

target = ?
に numpy int が入ると

assert operator.ndim == len(target) * 2

で止まります。numpy int が len に対応していないのが問題みたいです。

**Comment by ken-nakanishi** [comment]
Thank you for the bug report! This bug has been removed from version 0.1.7!
