### ISSUE TITLE
Travis CIの設定

### ISSUE THREAD

**Issue by y-yu** [ken-nakanishi/qupy#4]
#3 でTravis CIの設定ファイルが追加されましたが、Travis CI側で3分くらいで終わる設定をしないと有効になりません。

1. https://travis.org/ へアクセスし、GitHubのアカウントでユーザー登録する
2. https://travis-ci.org/account/repositories へアクセスし、リポジトリ一覧から`qupy`を探しだす
3. 右にあるボタンを押して有効にする
    - ![image](https://user-images.githubusercontent.com/612043/49029286-94251e00-f1e7-11e8-8e87-6c7d17e242f2.png)
    - 有効になると👆 のようになる

有効になったかどうかを確かめるために、適当なブランチを作ってそれをpushしてみるとよいでしょう。

**Comment by ken-nakanishi** [comment]
ありがとうございます！設定いたしました。
