### ISSUE TITLE
Expectation value

### ISSUE THREAD

**Issue by josep-lumbreras** [ken-nakanishi/qupy#6]
There will be an option to do expectation values of Hermatian operators (e.g energy) using the GPU?
It would be very useful.

**Comment by ken-nakanishi** [comment]
A few minutes ago, I released QuPy v1!
You can calculate expectation values quickly using GPU now.

**Comment by josep-lumbreras** [comment]
Sorry, did you deleate the examples where they show how to calculate with the GPU?

**Comment by ken-nakanishi** [comment]
I made it possible to use the same code on CPU and GPU.
Please update v1.1.0.
Please do `export QUPY_GPU=0` before you run your code, if you use GPU.

**Comment by josep-lumbreras** [comment]
Im getting this error when I try to run with GPU:

if device >= 0:
TypeError: '>=' not supported between instances of 'str' and 'int'

In version 1.0 it worked fine for me.

**Comment by ken-nakanishi** [comment]
Thank you for your report!
Could you try v1.1.1?

**Comment by josep-lumbreras** [comment]
Now works fine!
If i dont set QUPY_GPU, all the program will be running on the CPU?

I have been trying a program where im using a variational quantum algorithm
(i miniminize an energy tunning some parameters of the circuit) and the program 
runs faster on the CPU. Maybe since the minimization runs on the CPU (im using minimization 
methods from scipy) the communication between GPU and CPU makes the program slower?

Thanks for your attention!

**Comment by ken-nakanishi** [comment]
> If i dont set QUPY_GPU, all the program will be running on the CPU?

Yes! If you don't set `QUPY_GPU` or you set `QUPY_GPU=-1`, all the program will be running on the CPU.

> the communication between GPU and CPU makes the program slower?

Communication of variational quantum circuit parameters between CPU and GPU doesn't make so slower, I think.

**Comment by josep-lumbreras** [comment]
Can i send you a python script that im using? 
Im running a circuit with 8 qubits and using the program with CPU takes like 5 seconds and with GPU 50 seconds. It is the same script, i change only the QUPY_GPU to -1 (CPU) and to 0 for GPU.

**Comment by ken-nakanishi** [comment]
OK. I'll check it!

**Comment by josep-lumbreras** [comment]
I send you an email. Thanks for your attention!

**Comment by ken-nakanishi** [comment]
**Summary**

The cause of the slowdown is probably in the importing part.
This overhead is probably inevitable when using GPU.

```
# test01.py
import time
start = time.time()
from qupy import Qubits
print(time.time() - start)
```

```
$ export QUPY_GPU=-1
$ python test01.py
0.18606972694396973
$ export QUPY_GPU=0
$ python test01.py
3.443936586380005
```
